name: 'Setup gcloud environment'
description: 'Setup a gcloud environment and add it to the PATH'
author: 'GoogleCloudPlatform'
inputs:
  version:
    description: 'The version of the gcloud SDK to be installed.  Example: 270.0.0'
    default: '270.0.0'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
